  
language: android
jdk: oraclejdk8
os: linux
dist: xenial

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-27

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

script:
    - git update-index --chmod=+x gradlew
    - ./gradlew build
    
deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  name: Sensors-build-$TRAVIS_TAG
  release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  overwrite: true
  target_commitish: $TRAVIS_COMMIT

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
