language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools

    - build-tools-29.0.2

    - android-27

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21


before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

script:
    - git update-index --chmod=+x gradlew
    - ./gradlew build
